menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
search: true

widgets: 
#- tagcloud 
- category
- recent_posts
#- recent_comment

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false

fancybox: true

google_analytics: UA-51515330-1

